### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/bundlex#25]
Today, running mix under high CPU usage i got the following error:
```
 iex -S mix
Erlang/OTP 21 [erts-10.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]


18:06:10.957 [info]  [Porcelain]: goon executable not found
 
18:06:10.957 [info]  [Porcelain]: falling back to the basic driver.

18:06:10.957 [info]  [Porcelain]: (set `config :porcelain, driver: Porcelain.Driver.Basic` or `config :porcelain, goon_warn_if_missing: false` to disable this warning)
Bundlex: !!! Bulding Bundlex Library: :membrane_common_c
Bundlex: ### Reading project
Bundlex: ### Target platform
Bundlex:   - Building for platform linux
Bundlex: ### Toolchain
Bundlex: ### Resolving NIFs
Bundlex:   - Found Erlang includes: ["/usr/lib/erlang/usr/include"]
Bundlex:   - Ignoring export-only nif :membrane
Bundlex:   - Ignoring export-only nif :membrane_ringbuffer
Bundlex:   - Parsing NIF :membrane_shm_payload
Bundlex:   - Parsing NIF :membrane
Bundlex:   - Ignoring export-only nif :membrane_shm_payload_lib
Bundlex: ### Building
Bundlex:   - Running build script
** (File.Error) could not change mode for "bundlex_tmp.sh": no such file or directory
    (elixir) lib/file.ex:1559: File.chmod!/2
    lib/bundlex/build_script.ex:48: Bundlex.BuildScript.store/3
    lib/bundlex/build_script.ex:56: Bundlex.BuildScript.store_tmp/3
    lib/tasks/compile.bundlex.ex:63: Mix.Tasks.Compile.Bundlex.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
```
Looks like race condition to me, running it again worked OK

**Comment by bblaszkow06** [comment]
Caused by 2 compilations running at the same time and both using `bundlex_tmp.sh`. Fixed by #28
